package fr.alexdoru.partymod.ui;

import fr.alexdoru.partymod.*;
import fr.alexdoru.partymod.core.*;
import fr.alexdoru.partymod.data.LocalStore;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.*;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.network.NetworkPlayerInfo;
import net.minecraft.util.ResourceLocation;
import org.lwjgl.input.*;
import org.lwjgl.opengl.GL11;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.*;

/** Snapshot-based list: async results cannot move the selected row under a click. */
public final class PartyScreen extends GuiScreen {
    private static final int W=940,H=560,BG=0xff12151f,CARD=0xff1b2030,SOFT=0xff242b3e,ACCENT=0xff9b8aff,TEXT=0xffedf0f8,MUTED=0xff929db6,GREEN=0xff86d8b0,AMBER=0xffebc287;
    private static final String[] TABS={"Players","Review queue","Event log","Event desk"},FILTERS={"All","Review","Pending","Unassessed"},SORTS={"Joined","Name","Review"};
    private final List<Hit> hits=new ArrayList<>();
    private final List<String> order=new ArrayList<>();
    private GuiTextField search,note,waitName;
    private String tab="Players",filter="All",sort="Joined",selected="",query="";
    private int scroll,detailScroll;
    private boolean initialized;
    private long noteGeneration=-1,noteMembership=-1;private String noteUuid="";
    private float scale,ox,oy;
    private String confirm="";private long confirmGeneration,confirmMembership;private String confirmName="";private MemberTicket confirmationTicket;
    private static final class Hit {final int x,y,w,h;final Runnable action;Hit(int x,int y,int w,int h,Runnable a){this.x=x;this.y=y;this.w=w;this.h=h;action=a;}boolean has(int mx,int my){return mx>=x&&my>=y&&mx<x+w&&my<y+h;}}
    @Override public void initGui(){scale=Math.min(width/(float)(W+24),height/(float)(H+24));ox=(width-W*scale)/2;oy=(height-H*scale)/2;search=new GuiTextField(1,fontRendererObj,40,118,360,22);search.setMaxStringLength(32);search.setEnableBackgroundDrawing(false);search.setText(query);search.setTextColor(TEXT);note=new GuiTextField(2,fontRendererObj,602,373,290,20);note.setMaxStringLength(1000);note.setEnableBackgroundDrawing(false);note.setTextColor(TEXT);String waiting=waitName==null?"":waitName.getText();waitName=new GuiTextField(3,fontRendererObj,50,402,255,20);waitName.setMaxStringLength(16);waitName.setEnableBackgroundDrawing(false);waitName.setTextColor(TEXT);if(!initialized){filter=PartyMod.runtime.store.filter;sort=PartyMod.runtime.store.sort;initialized=true;}waitName.setText(waiting);Keyboard.enableRepeatEvents(true);refreshOrder();loadNote();}
    @Override public boolean doesGuiPauseGame(){return false;}
    @Override public void onGuiClosed(){Keyboard.enableRepeatEvents(false);PartyMod.runtime.store.filter=filter;PartyMod.runtime.store.sort=sort;PartyMod.runtime.store.touch();PartyMod.runtime.store.flush(true);}
    private int mx(int x){return (int)((x-ox)/scale);}private int my(int y){return (int)((y-oy)/scale);}
    @Override public void drawScreen(int mouseX,int mouseY,float partial){drawRect(0,0,width,height,0xc010121b);int mx=mx(mouseX),my=my(mouseY);hits.clear();GlStateManager.pushMatrix();GlStateManager.translate(ox,oy,0);GlStateManager.scale(scale,scale,1);round(0,0,W,H,14,BG);round(24,20,34,34,9,ACCENT);text("P",35,29,0xff171927,1.7f);text("PARTYMOD",72,20,TEXT,1.8f);text("An organised party. A clearer event.",73,44,MUTED,1);pill(720,22,PartyMod.runtime.active()?"HYPIXEL · ACTIVE":"LOCAL VIEW",PartyMod.runtime.active()?GREEN:MUTED);button(817,20,98,32,"OneConfig",()->PartyMod.config.openGui(),mx,my,false);
        int tx=25;for(String name:TABS){int tw=fontRendererObj.getStringWidth(name)+38;boolean chosen=tab.equals(name);button(tx,76,tw,30,name,()->{tab=name;scroll=detailScroll=0;confirm="";refreshOrder();},mx,my,chosen);tx+=tw+7;}
        if(tab.equals("Players")||tab.equals("Review queue"))drawRoster(mx,my);else if(tab.equals("Event log"))drawLog();else drawDesk(mx,my);
        drawRect(24,H-52,W-24,H-51,SOFT);text(PartyMod.runtime.state.members().size()+" / "+(int)PartyMod.config.capacity+" members",28,H-33,TEXT,1);text(PartyMod.runtime.state.countReview()+" reviews  ·  "+PartyMod.runtime.state.countPending()+" pending  ·  "+PartyMod.runtime.actions.size()+" actions",207,H-33,MUTED,1);
        button(602,H-40,139,28,"Sync roster",()->PartyMod.runtime.sync(),mx,my,false);button(750,H-40,163,28,"Pre-queue check",()->{tab="Event desk";scroll=0;},mx,my,true);
        if(!confirm.isEmpty())drawConfirm(mx,my);
        GlStateManager.popMatrix();super.drawScreen(mouseX,mouseY,partial);
    }
    private void refreshOrder(){query=search==null?query:search.getText();List<Member> list=new ArrayList<>(PartyMod.runtime.state.members());list.removeIf(m->!matches(m));Comparator<Member> compare=sort.equals("Name")?Comparator.comparing(m->m.name.toLowerCase(Locale.ROOT)):sort.equals("Review")?Comparator.<Member>comparingInt(m->m.needsReview()?0:1).thenComparing(m->m.name):Comparator.comparingLong(m->m.joinedAt);list.sort(compare);order.clear();for(Member m:list)order.add(m.key);scroll=Math.max(0,Math.min(scroll,Math.max(0,order.size()-6)));if(!order.contains(selected)){selected=order.isEmpty()?"":order.get(0);loadNote();}}
    private boolean matches(Member m){return RosterView.matches(m,query,filter,tab.equals("Review queue"));}
    private void reconcileSelection(){Member m=PartyMod.runtime.state.get(selected);if(noteGeneration!=PartyMod.runtime.state.generation||noteMembership!=(m==null?0:m.membershipId)||!noteUuid.equals(m==null?"":m.uuid)){loadNote();note.setFocused(false);}}
    private void reconcileOrder(){order.removeIf(key->PartyMod.runtime.state.get(key)==null);for(Member m:PartyMod.runtime.state.members())if(!order.contains(m.key)&&matches(m))order.add(m.key);scroll=Math.max(0,Math.min(scroll,Math.max(0,order.size()-6)));}
    private void drawRoster(int mx,int my){reconcileOrder();reconcileSelection();round(26,114,523,32,7,CARD);if(search.getText().isEmpty()&&!search.isFocused())text("Search players…",40,125,MUTED,1);search.drawTextBox();button(420,116,121,28,"Refresh order",this::refreshOrder,mx,my,false);
        button(27,156,150,28,"Filter: "+(tab.equals("Review queue")?"Review":filter),()->{if(tab.equals("Review queue"))return;filter=FILTERS[(Arrays.asList(FILTERS).indexOf(filter)+1)%FILTERS.length];refreshOrder();},mx,my,false);button(187,156,150,28,"Sort: "+sort,()->{sort=SORTS[(Arrays.asList(SORTS).indexOf(sort)+1)%SORTS.length];refreshOrder();},mx,my,false);text("Order held while you review",351,166,MUTED,1);
        if(order.isEmpty()){round(27,198,522,284,10,CARD);text(tab.equals("Review queue")?"Nothing needs review":"Your roster starts here",58,254,TEXT,1.6f);wrapped(tab.equals("Review queue")?"No current members match this view. Unassessed players are shown separately; they have not passed screening.":"Join Hypixel, then sync your party. Membership comes from server messages; old rosters are never restored as current.",58,294,440,MUTED,1);}
        for(int index=scroll,row=0;index<order.size()&&row<6;index++,row++){Member m=PartyMod.runtime.state.get(order.get(index));if(m==null)continue;int y=198+row*49;round(27,y,522,43,8,m.key.equals(selected)?SOFT:CARD);if(m.key.equals(selected))round(27,y+6,3,31,1,ACCENT);head(m,40,y+9);text(m.name,78,y+8,TEXT,1.15f);text(m.role.name().toLowerCase(Locale.ROOT)+(m.disconnectedAt>0?" · disconnected":""),78,y+25,MUTED,0.95f);String label=m.needsReview()?"Review":m.approved?"Reviewed":!m.reasons.isEmpty()&&!m.needsReview()?"Dismissed":m.status==Member.Status.PENDING?"Pending":m.status==Member.Status.LOADED||m.status==Member.Status.CACHED?"No flags":"Not assessed";pill(390,y+12,label,m.needsReview()?AMBER:m.approved?GREEN:MUTED);final String key=m.key;hits.add(new Hit(27,y,522,43,()->{selected=key;detailScroll=0;loadNote();}));}
        if(order.size()>6)text((scroll+1)+"–"+Math.min(scroll+6,order.size())+" of "+order.size()+" · scroll / arrow keys",40,496,MUTED,0.9f);
        drawDetails(mx,my);
    }
    private void loadNote(){Member m=PartyMod.runtime.state.get(selected);noteGeneration=PartyMod.runtime.state.generation;noteMembership=m==null?0:m.membershipId;noteUuid=m==null?"":m.uuid;if(note!=null)note.setText(m==null?"":PartyMod.runtime.store.record(m).note);}
    private Runnable bound(Member member,Runnable action){MemberTicket ticket=new MemberTicket(PartyMod.runtime.state,member);return ()->{if(ticket.valid(PartyMod.runtime.state))action.run();else PartyMod.runtime.notify("stale-selection","Player or evidence changed — review the current details",true);};}
    private void drawDetails(int mx,int my){round(569,114,344,392,10,CARD);Member m=PartyMod.runtime.state.get(selected);if(m==null){text("Select a player",593,145,TEXT,1.5f);wrapped("Details, evidence and host controls appear here.",593,180,290,MUTED,1);return;}text(m.name,593,132,TEXT,1.7f);text(m.label(),594,157,m.needsReview()?AMBER:MUTED,1);LocalStore.Record record=PartyMod.runtime.store.record(m);List<String> lines=new ArrayList<>();
        if(m.stats!=null){PlayerStats s=m.stats;lines.add("Network level: "+number(s.networkLevel));lines.add("Recorded wins + losses: "+number(s.games()));lines.add("Final kills / deaths: "+number(s.finals)+" / "+number(s.finalDeaths));lines.add("FKD: "+number(s.fkd())+"   W/L: "+number(s.wl()));lines.add("First login: "+date(s.firstLogin));lines.add("Fetched: "+date(s.fetchedAt)+" · "+(m.status==Member.Status.CACHED?"cached":"loaded"));lines.add("Source: "+s.source);lines.add("Mojang-name identity; nick identity unverified");lines.addAll(s.warnings);}else{lines.add(m.error.isEmpty()?"Data not assessed":m.error);lines.add("Configure stats access under OneConfig > Data");}
        if(!PartyMod.runtime.store.stored(record))lines.add("Record limit reached: this note is currently unsaved");if(!record.migratedNote.isEmpty())lines.add("Retained name note: "+record.migratedNote);lines.add("Last local MW sighting: "+date(record.lastMwSighting));lines.add("Outside games and competitive bans: unknown");if(!m.reasons.isEmpty()){lines.add("REVIEW REASONS");lines.addAll(m.reasons);}else lines.add("No configured reasons; this is not proof of legitimacy.");
        List<String> wrapped=new ArrayList<>();for(String line:lines)wrapped.addAll(fontRendererObj.listFormattedStringToWidth(line,300));detailScroll=Math.max(0,Math.min(detailScroll,Math.max(0,wrapped.size()-12)));for(int i=detailScroll,y=184;i<wrapped.size()&&y<332;i++,y+=13)text(wrapped.get(i),594,y,wrapped.get(i).equals("REVIEW REASONS")?AMBER:MUTED,0.95f);if(wrapped.size()>12)text("Scroll details for all evidence",594,343,ACCENT,0.8f);
        text("HOST NOTE",595,358,MUTED,0.85f);round(593,370,301,29,5,SOFT);note.drawTextBox();
        button(592,408,145,27,m.approved?"Reviewed":"Approve for event",bound(m,()->{m.approved=true;PartyMod.runtime.notify("approve:"+m.key,m.name+" reviewed by host",false);}),mx,my,true);button(748,408,145,27,"Dismiss reasons",bound(m,()->m.dismissedFingerprint=m.fingerprint()),mx,my,false);
        button(592,443,92,25,"Remove…",bound(m,()->confirm("remove",m)),mx,my,false);button(693,443,92,25,"Block…",bound(m,()->confirm("block",m)),mx,my,false);button(795,443,98,25,"Ignore…",bound(m,()->confirm("ignore",m)),mx,my,false);
        button(592,478,145,23,record.blocked?"Unmark host block":"Host blocklist",bound(m,()->{LocalStore.Record current=PartyMod.runtime.store.record(m);current.blocked=!current.blocked;PartyMod.runtime.store.touch();PartyMod.runtime.reassess();}),mx,my,false);button(748,478,145,23,"Delete local record…",bound(m,()->confirm("delete",m)),mx,my,false);
    }
    private void drawLog(){round(27,117,886,387,10,CARD);text("EVENT LOG",49,137,TEXT,1.2f);text("Operational outcomes and review notices · newest first",49,160,MUTED,1);List<Notifications.Entry> entries=new ArrayList<>(PartyMod.runtime.notifications.log);scroll=Math.max(0,Math.min(scroll,Math.max(0,entries.size()-19)));if(entries.isEmpty())text("No events yet. Your party activity will appear here.",49,216,MUTED,1);for(int i=scroll,y=193;i<entries.size()&&y<482;i++,y+=16){Notifications.Entry e=entries.get(i);text(new SimpleDateFormat("HH:mm:ss").format(new Date(e.time)),49,y,MUTED,0.9f);text(fontRendererObj.trimStringToWidth(e.text,753),112,y,e.operational?AMBER:TEXT,0.95f);}}
    private void drawDesk(int mx,int my){round(27,117,430,269,10,CARD);text("PRE-QUEUE CHECK",49,140,TEXT,1.4f);int y=176;for(String line:PartyMod.runtime.precheck()){if(line.equals("PRE-QUEUE REVIEW"))continue;List<String> pieces=fontRendererObj.listFormattedStringToWidth(line,380);for(String p:pieces){text(p,49,y,MUTED,1);y+=16;}}button(49,335,185,30,"Start readiness round",()->PartyMod.runtime.startReady(),mx,my,true);button(246,335,186,30,"Mark selected ready",()->{Member m=PartyMod.runtime.state.get(selected);if(m!=null&&!PartyMod.runtime.state.round.isEmpty())m.ready=true;},mx,my,false);
        round(476,117,437,387,10,CARD);text("LOCAL WAITLIST",497,140,TEXT,1.4f);text("Invitations are host-controlled; slots are advisory.",497,165,MUTED,0.95f);List<LocalStore.WaitEntry> entries=PartyMod.runtime.store.waitlist;int start=Math.max(0,Math.min(scroll,Math.max(0,entries.size()-9)));for(int i=start,row=0;i<entries.size()&&row<9;i++,row++){LocalStore.WaitEntry e=entries.get(i);int wy=193+row*29;text(e.name,497,wy,TEXT,1);text(fontRendererObj.trimStringToWidth(e.status,145),618,wy,MUTED,0.85f);button(775,wy-5,65,23,"Invite",()->PartyMod.runtime.invite(e),mx,my,false);button(846,wy-5,48,23,"Drop",()->{PartyMod.runtime.store.dropWait(e);},mx,my,false);}if(entries.isEmpty())wrapped("Add names below. No invitation is sent until you choose Invite.",497,215,360,MUTED,1);
        round(27,398,430,106,10,CARD);round(44,399,264,29,5,SOFT);if(waitName.getText().isEmpty()&&!waitName.isFocused())text("Username for the waitlist",50,412,MUTED,1);waitName.drawTextBox();button(320,399,116,29,"Add locally",()->{if(PartyMod.runtime.store.addWait(waitName.getText()))waitName.setText("");},mx,my,true);text("Disconnect grace: "+(int)PartyMod.config.grace+" seconds",49,442,TEXT,1);long expired=PartyMod.runtime.state.members().stream().filter(m->m.disconnectedAt>0&&System.currentTimeMillis()-m.disconnectedAt>PartyMod.config.grace*1000).count();text(expired+" grace periods expired · no automatic removal",49,466,MUTED,0.95f);
    }
    private void confirm(String action,Member m){if(PartyMod.runtime.state.get(m.name)!=m)return;if(!PartyMod.config.confirmActions&&!action.equals("delete")){execute(action,m);return;}confirm=action;confirmationTicket=new MemberTicket(PartyMod.runtime.state,m);confirmName=m.name;confirmGeneration=PartyMod.runtime.state.generation;confirmMembership=m.membershipId;}
    private void execute(String action,Member m){switch(action){case "remove":PartyMod.runtime.remove(m);break;case "block":PartyMod.runtime.block(m);break;case "ignore":PartyMod.runtime.ignore(m);break;case "delete":PartyMod.runtime.store.delete(m);m.approved=false;m.dismissedFingerprint="";loadNote();PartyMod.runtime.reassess();break;default:break;}}
    private void drawConfirm(int mx,int my){drawRect(0,0,W,H,0xb010121b);hits.clear();round(244,190,452,177,12,CARD);text(confirm.equals("delete")?"Delete this player's local record?":"Confirm "+confirm,268,213,TEXT,1.5f);text(confirmName,269,245,ACCENT,1.2f);wrapped(confirm.equals("remove")?(PartyMod.config.autoBlock?"A confirmed kick will also queue /block add. Ignore is a separate action.":"This removes the player from this party. Ignore and block are separate actions."):confirm.equals("delete")?"Deletes your saved note, local blocklist entry and attendance for this identity.":"This changes your Hypixel "+confirm+" list. Party removal is a separate action.",269,269,396,MUTED,1);button(268,324,183,27,"Cancel",()->confirm="",mx,my,false);button(466,324,206,27,"Confirm "+confirm,()->{Member m=PartyMod.runtime.state.get(confirmName);if((confirm.equals("delete")||PartyMod.runtime.active())&&PartyMod.runtime.state.valid(confirmGeneration,confirmName,confirmMembership)&&confirmationTicket!=null&&confirmationTicket.valid(PartyMod.runtime.state)){execute(confirm,m);}else PartyRuntime.chat("Action cancelled — party context changed.");confirm="";},mx,my,true);}
    @Override protected void mouseClicked(int x,int y,int button)throws IOException{if(button!=0)return;reconcileSelection();int mx=mx(x),my=my(y);if(confirm.isEmpty()){if(tab.equals("Players")||tab.equals("Review queue")){search.mouseClicked(mx,my,button);note.mouseClicked(mx,my,button);}if(tab.equals("Event desk"))waitName.mouseClicked(mx,my,button);}for(Hit hit:new ArrayList<>(hits))if(hit.has(mx,my)){hit.action.run();break;}}
    @Override protected void keyTyped(char typed,int key)throws IOException{reconcileSelection();if(!confirm.isEmpty()){if(key==Keyboard.KEY_ESCAPE)confirm="";return;}if(key==Keyboard.KEY_ESCAPE){mc.displayGuiScreen(null);return;}if((tab.equals("Players")||tab.equals("Review queue"))&&search.textboxKeyTyped(typed,key)){refreshOrder();return;}if((tab.equals("Players")||tab.equals("Review queue"))&&note.textboxKeyTyped(typed,key)){Member m=PartyMod.runtime.state.get(selected);if(m!=null){PartyMod.runtime.store.record(m).note=note.getText();PartyMod.runtime.store.touch();}return;}if(tab.equals("Event desk")&&waitName.textboxKeyTyped(typed,key))return;if(key==Keyboard.KEY_UP||key==Keyboard.KEY_DOWN){int next=order.indexOf(selected)+(key==Keyboard.KEY_DOWN?1:-1);if(next>=0&&next<order.size()){selected=order.get(next);scroll=Math.max(0,Math.min(next,Math.max(0,order.size()-6)));detailScroll=0;loadNote();}}if(key==Keyboard.KEY_TAB){String next=TABS[(Arrays.asList(TABS).indexOf(tab)+1)%TABS.length];tab=next;scroll=0;refreshOrder();}}
    @Override public void handleMouseInput()throws IOException{super.handleMouseInput();int wheel=Mouse.getEventDWheel();if(wheel==0||!confirm.isEmpty())return;int x=Mouse.getEventX()*width/mc.displayWidth,y=height-Mouse.getEventY()*height/mc.displayHeight-1;if(mx(x)>569&&(tab.equals("Players")||tab.equals("Review queue")))detailScroll+=wheel<0?2:-2;else scroll=Math.max(0,scroll+(wheel<0?1:-1));}
    private void button(int x,int y,int w,int h,String label,Runnable action,int mx,int my,boolean primary){boolean hover=mx>=x&&my>=y&&mx<x+w&&my<y+h;round(x,y,w,h,6,primary?(hover?0xffb0a2ff:ACCENT):(hover?0xff30394f:SOFT));int tw=fontRendererObj.getStringWidth(label);text(label,x+(w-tw)/2,y+(h-8)/2,primary?0xff171927:TEXT,1);hits.add(new Hit(x,y,w,h,action));}
    private void pill(int x,int y,String label,int color){int w=fontRendererObj.getStringWidth(label)+16;round(x,y,w,19,5,(color&0xffffff)|0x22000000);text(label,x+8,y+6,color,0.9f);}
    private void head(Member m,int x,int y){NetworkPlayerInfo info=mc.getNetHandler()==null?null:mc.getNetHandler().getPlayerInfo(m.name);if(info!=null){GlStateManager.color(1,1,1,1);mc.getTextureManager().bindTexture(info.getLocationSkin());Gui.drawScaledCustomSizeModalRect(x,y,8,8,8,8,24,24,64,64);}else{round(x,y,24,24,6,SOFT);text(m.name.substring(0,1).toUpperCase(Locale.ROOT),x+8,y+8,ACCENT,1);}}
    private String date(Long time){return time==null||time<=0?"Unknown":new SimpleDateFormat("dd MMM yyyy",Locale.ROOT).format(new Date(time));}
    private String number(Number n){return n==null?"Unknown":n instanceof Double?String.format(Locale.ROOT,"%.2f",n.doubleValue()):n.toString();}
    private void wrapped(String text,int x,int y,int width,int color,float size){for(String line:fontRendererObj.listFormattedStringToWidth(text,(int)(width/size))){text(line,x,y,color,size);y+=(int)(13*size);}}
    private void text(String text,int x,int y,int color,float size){GlStateManager.pushMatrix();GlStateManager.translate(x,y,0);GlStateManager.scale(size,size,1);fontRendererObj.drawString(text,0,0,color);GlStateManager.popMatrix();}
    public static void round(float x,float y,float w,float h,float radius,int color){boolean cull=GL11.glIsEnabled(GL11.GL_CULL_FACE),blend=GL11.glIsEnabled(GL11.GL_BLEND),texture=GL11.glIsEnabled(GL11.GL_TEXTURE_2D);int src=GL11.glGetInteger(32969),dst=GL11.glGetInteger(32968),srcAlpha=GL11.glGetInteger(32971),dstAlpha=GL11.glGetInteger(32970);GlStateManager.disableCull();GlStateManager.enableBlend();GlStateManager.disableTexture2D();GlStateManager.tryBlendFuncSeparate(770,771,1,0);GlStateManager.color((color>>16&255)/255f,(color>>8&255)/255f,(color&255)/255f,(color>>>24)/255f);GL11.glBegin(GL11.GL_TRIANGLE_FAN);GL11.glVertex2f(x+w/2,y+h/2);for(int corner=0;corner<4;corner++){float cx=corner==0||corner==3?x+radius:x+w-radius,cy=corner<2?y+radius:y+h-radius;for(int step=0;step<=8;step++){double angle=Math.toRadians(180+corner*90+step*90/8.0);GL11.glVertex2f(cx+(float)Math.cos(angle)*radius,cy+(float)Math.sin(angle)*radius);}}GL11.glVertex2f(x,y+radius);GL11.glEnd();if(cull)GlStateManager.enableCull();if(texture)GlStateManager.enableTexture2D();else GlStateManager.disableTexture2D();if(blend)GlStateManager.enableBlend();else GlStateManager.disableBlend();GlStateManager.tryBlendFuncSeparate(src,dst,srcAlpha,dstAlpha);GlStateManager.color(1,1,1,1);}
    public static void drawToast(Notifications.Entry entry,int width){Minecraft mc=Minecraft.getMinecraft();String label=mc.fontRendererObj.trimStringToWidth(entry.text,280);int w=Math.min(310,mc.fontRendererObj.getStringWidth(label)+24);round(width-w-14,16,w,43,7,CARD);mc.fontRendererObj.drawString(entry.operational?"PARTY UPDATE":"PARTY REVIEW",width-w-2,24,entry.operational?AMBER:ACCENT);mc.fontRendererObj.drawString(label,width-w-2,39,TEXT);}
}

