package fr.alexdoru.partymod;

import fr.alexdoru.partymod.core.*;
import fr.alexdoru.partymod.data.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import com.sun.net.httpserver.HttpServer;
import java.net.InetSocketAddress;

public class AuditLifecycleTest {
    private final long now=2000000000000L;
    private PartyState party(){PartyState s=new PartyState();s.role("Host",Member.Role.LEADER,now);s.join("Alice",now);return s;}
    private ActionQueue.Action action(PartyState s,ActionQueue.Kind kind,String name){return new ActionQueue.Action(kind,name,"/command",s.generation,0,now);}
    private boolean valid(PartyState s,ActionQueue.Action a,boolean autoBlock,boolean invite){return ActionPolicy.valid(a,s,"Host",true,true,autoBlock,true,90,100,now,invite);}
    @Test public void automaticBlocksRecheckTheToggleButManualBlocksRemainAvailable(){PartyState s=party();ActionQueue.Action a=action(s,ActionQueue.Kind.BLOCK,"Alice");a.automatic=true;assertTrue(valid(s,a,true,false));assertFalse(valid(s,a,false,false));a.automatic=false;assertTrue(valid(s,a,false,false));}
    @Test public void queuedReadyRoundCannotOutliveLeadership(){PartyState s=party();ActionQueue.Action a=action(s,ActionQueue.Kind.READY,"");a.context=s.startReadyRound();assertTrue(valid(s,a,true,false));s.role("Alice",Member.Role.LEADER,now);assertFalse(valid(s,a,true,false));}
    @Test public void queuedReadyRoundCannotUseAnOldIdentifier(){PartyState s=party();ActionQueue.Action a=action(s,ActionQueue.Kind.READY,"");a.context=s.startReadyRound();s.startReadyRound();assertFalse(valid(s,a,true,false));}
    @Test public void droppedInvitationsCannotBeSent(){PartyState s=party();ActionQueue.Action a=action(s,ActionQueue.Kind.INVITE,"Replacement");assertTrue(valid(s,a,true,true));assertFalse(valid(s,a,true,false));s.role("Host",Member.Role.MEMBER,now);assertFalse(valid(s,a,true,true));}
    @Test public void sessionChangeCancelsAutomaticBlock(){PartyState s=party();ActionQueue.Action a=action(s,ActionQueue.Kind.BLOCK,"Alice");a.automatic=true;s.reset();assertFalse(valid(s,a,true,false));}
    @Test public void automaticRemovalRejectsStaleAndUnavailableStats(){PartyState s=party();Member m=s.get("Alice");m.ageCandidate=true;m.stats=new PlayerStats();m.stats.firstLogin=now-86400000L;m.stats.fetchedAt=now;m.status=Member.Status.LOADED;ActionQueue.Action a=action(s,ActionQueue.Kind.NEW_ACCOUNT_REMOVE,"Alice");a=new ActionQueue.Action(a.kind,a.name,a.command,s.generation,m.membershipId,now);assertTrue(valid(s,a,true,false));m.status=Member.Status.UNAVAILABLE;assertFalse(valid(s,a,true,false));m.status=Member.Status.CACHED;m.stats.fetchedAt=now-2*86400000L;assertFalse(valid(s,a,true,false));}
    @Test public void aRealNewPartyAllowsOneRecoveryAfterNoParty(){SyncPolicy p=new SyncPolicy();assertTrue(p.activation(true));p.partyEnded();assertFalse(p.activation(true));assertFalse(p.recovery());p.partyJoined();assertTrue(p.recovery());assertFalse(p.recovery());p.partyEnded();assertFalse(p.activation(true));assertFalse(p.recovery());}
    @Test public void reviewQueueIgnoresPlayersPendingFilter(){Member m=new Member("Alice",1,1);m.status=Member.Status.LOADED;m.reasons.add("Review");assertTrue(RosterView.matches(m,"","Pending",true));assertFalse(RosterView.matches(m,"","Pending",false));m.approved=true;assertFalse(RosterView.matches(m,"","All",true));}
    @Test public void cancelledDataRemainsInUnassessedView(){Member m=new Member("Alice",1,1);m.status=Member.Status.CANCELLED;assertTrue(RosterView.matches(m,"","Unassessed",false));}
    @Test public void invalidTokensNeverReachHeadersOrEchoTheSecret()throws Exception{HttpServer server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);AtomicInteger hits=new AtomicInteger();server.createContext("/",e->{hits.incrementAndGet();e.close();});server.start();DataClient client=new DataClient();try{client.configure("http://127.0.0.1:"+server.getAddress().getPort(),"secret-value\nInjected",120,60);CountDownLatch done=new CountDownLatch(1);AtomicReference<String> error=new AtomicReference<>();client.request("Alice",r->{error.set(r.error);done.countDown();});assertTrue(done.await(3,TimeUnit.SECONDS));assertEquals(0,hits.get());assertFalse(error.get().contains("secret-value"));assertTrue(error.get().contains("configuration"));}finally{client.shutdown();server.stop(0);}}
    @Test public void expiryCallbackMayEnqueueWithoutKillingThePump()throws Exception{DataClient client=new DataClient();try{synchronized(client){client.configure("https://unused.invalid","",120,1);Field next=DataClient.class.getDeclaredField("nextRequest");next.setAccessible(true);next.setLong(client,Long.MAX_VALUE);client.request("Alice",r->client.request("Bob",ignored->{}));Field jobsField=DataClient.class.getDeclaredField("jobs");jobsField.setAccessible(true);Map<?,?> jobs=(Map<?,?>)jobsField.get(client);Object job=jobs.values().iterator().next();Field deadline=job.getClass().getDeclaredField("deadline");deadline.setAccessible(true);deadline.setLong(job,0);Method pump=DataClient.class.getDeclaredMethod("pump");pump.setAccessible(true);pump.invoke(client);assertEquals(1,client.queued());}}finally{client.shutdown();}}
    @Test public void cancelledUnsentBlockDoesNotSuppressAnExplicitRetry(){PartyState s=party();ActionQueue q=new ActionQueue();ActionQueue.Action a=action(s,ActionQueue.Kind.BLOCK,"Alice");q.enqueue(a);q.tick(now,1250,new ActionQueue.Transport(){public boolean valid(ActionQueue.Action x){return false;}public void send(String command){fail();}public void result(ActionQueue.Action x,String outcome){}});assertTrue(q.enqueue(action(s,ActionQueue.Kind.BLOCK,"Alice")));}
    @Test public void cancellationAllowsCallbackToCreateIndependentWork()throws Exception{DataClient client=new DataClient();try{synchronized(client){client.configure("https://unused.invalid","",120,1);Field next=DataClient.class.getDeclaredField("nextRequest");next.setAccessible(true);next.setLong(client,Long.MAX_VALUE);client.request("Alice",r->client.request("Bob",ignored->{}));client.cancel();assertEquals(1,client.queued());}}finally{client.shutdown();}}
    @Test public void hundredJoinBurstDeduplicatesAndCancelsEverySubscriber()throws Exception{DataClient client=new DataClient();try{synchronized(client){client.configure("https://unused.invalid","",120,30);Field next=DataClient.class.getDeclaredField("nextRequest");next.setAccessible(true);next.setLong(client,Long.MAX_VALUE);AtomicInteger cancelled=new AtomicInteger();for(int i=0;i<100;i++)for(int copy=0;copy<2;copy++)client.request("Player"+i,r->{if(r.error.equals("Cancelled"))cancelled.incrementAndGet();});assertEquals(100,client.queued());client.cancel();assertEquals(200,cancelled.get());assertEquals(0,client.queued());}}finally{client.shutdown();}}
    @Test public void invalidAgeConfigurationCannotCauseMassRemoval(){PartyState s=party();Member m=s.get("Alice");m.ageCandidate=true;m.status=Member.Status.LOADED;m.stats=new PlayerStats();m.stats.firstLogin=now-86400000L;m.stats.fetchedAt=now;assertTrue(NewAccountPolicy.eligible(m,true,90,now));for(int days:new int[]{-1,0,366,Integer.MAX_VALUE})assertFalse(NewAccountPolicy.eligible(m,true,days,now));}
    @Test public void futureOrOveragedRostersNeverAuthorizeModeration(){PartyState s=party();s.synced=true;s.rosterAt=now;assertTrue(s.fresh(now+60000,120));assertFalse(s.fresh(now-1,120));assertFalse(s.fresh(now+301000,Long.MAX_VALUE));s.synced=false;assertFalse(s.fresh(now,120));}
}
