package fr.alexdoru.partymod;

import fr.alexdoru.partymod.core.*;
import fr.alexdoru.partymod.data.DataClient;
import com.google.gson.*;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;

public class PartyCoreTest {
    private PlayerStats stats(String json){return PlayerStats.parseSummary(new JsonParser().parse(json).getAsJsonObject());}
    @Test public void allRanksAndShortNamesAreRecognized(){for(String prefix:new String[]{"","[VIP] ","[MVP++] ","[ADMIN] ","[GM] ","[YOUTUBE] "}){PartyMessages.Event e=PartyMessages.parse(prefix+"A joined the party. ");assertEquals(PartyMessages.Type.JOIN,e.type);assertEquals("A",e.name);}}
    @Test public void partyChatCannotSpoofKick(){assertEquals(PartyMessages.Type.CHAT,PartyMessages.parse("Party > [MVP++] Bob: Alice has been removed from the party.").type);assertEquals(PartyMessages.Type.NONE,PartyMessages.parse("[MVP++] Bob: Alice has been removed from the party.").type);}
    @Test public void onlyKickMessagesProduceKickEvents(){assertEquals(PartyMessages.Type.KICK,PartyMessages.parse("[GM] Alice has been removed from the party.").type);assertEquals("Alice",PartyMessages.parse("You have kicked [VIP] Alice from the party!").name);assertEquals(PartyMessages.Type.LEFT,PartyMessages.parse("Alice has left the party.").type);assertEquals(PartyMessages.Type.DISCONNECT,PartyMessages.parse("Alice disconnected.").type);}
    @Test public void headerAndRoleRowsParse(){assertEquals(100,PartyMessages.parse("Party Members (100)").count);assertEquals(Arrays.asList("A","Alice","Bob"),PartyMessages.names("[VIP] A ● [GM] Alice ● Bob ●"));assertEquals(Member.Role.LEADER,PartyMessages.parse("Party Leader: [MVP++] Bob ●").role);}
    @Test public void exactServerScope(){assertTrue(PartyMessages.hypixel("mc.hypixel.net:25565"));assertTrue(PartyMessages.hypixel("HYPIXEL.NET"));assertFalse(PartyMessages.hypixel("hypixel.net.evil.test"));assertFalse(PartyMessages.hypixel("nothypixel.net"));}
    @Test public void rosterCommits100MembersAtomically(){PartyState s=new PartyState();s.beginSync(100,1);s.stage("Host",Member.Role.LEADER);for(int i=0;i<99;i++)s.stage("Player"+i,Member.Role.MEMBER);assertTrue(s.members().isEmpty());assertTrue(s.commitSync(2));assertEquals(100,s.members().size());assertTrue(s.synced);}
    @Test public void incompleteRosterDoesNotOverwrite(){PartyState s=new PartyState();s.join("Existing",1);s.beginSync(3,2);s.stage("Host",Member.Role.LEADER);s.stage("Alice",Member.Role.MEMBER);assertFalse(s.commitSync(3));assertNotNull(s.get("Existing"));s.syncFailed();assertFalse(s.synced);}
    @Test public void changedRosterInvalidatesSnapshot(){PartyState s=new PartyState();s.beginSync(2,1);s.stage("Host",Member.Role.LEADER);s.join("NewArrival",2);s.stage("Alice",Member.Role.MEMBER);assertFalse(s.commitSync(3));assertNotNull(s.get("NewArrival"));}
    @Test public void rosterNeedsExactlyOneLeader(){PartyState s=new PartyState();s.beginSync(1,1);s.stage("A",Member.Role.MEMBER);assertFalse(s.commitSync(2));}
    @Test public void staleAssessmentCannotApplyAfterRejoin(){PartyState s=new PartyState();Member first=s.join("Alice",1);long id=first.membershipId;s.leave("Alice");s.join("Alice",2);assertFalse(s.valid(s.generation,"Alice",id));}
    @Test public void togglesCancelAndCanResume(){PartyState s=new PartyState();Member m=s.join("Alice",1);m.status=Member.Status.PENDING;long old=s.generation;s.invalidateWork();assertEquals(Member.Status.CANCELLED,m.status);assertFalse(s.valid(old,"Alice",m.membershipId));assertTrue(s.valid(s.generation,"Alice",m.membershipId));}
    @Test public void resetRemovesCurrentMembership(){PartyState s=new PartyState();s.join("A",1);long old=s.generation;s.reset();assertTrue(s.members().isEmpty());assertTrue(s.generation>old);assertFalse(s.synced);}
    @Test public void successfulSyncStopsTimeoutClock(){PartyState s=new PartyState();s.beginSync(1,100);s.stage("Host",Member.Role.LEADER);assertTrue(s.commitSync(200));assertEquals(0,s.syncStartedAt);assertTrue(s.synced);s.beginSync(1,300);s.reset();assertEquals(0,s.syncStartedAt);}
    @Test public void disablingRequiresFreshSyncBeforeModeration(){PartyState s=new PartyState();s.beginSync(1,1);s.stage("Host",Member.Role.LEADER);assertTrue(s.commitSync(2));s.invalidateWork();assertFalse(s.synced);assertEquals(0,s.rosterAt);}
    @Test public void selfJoiningSignalsNewPartySession(){assertEquals(PartyMessages.Type.SELF_JOIN,PartyMessages.parse("You have joined [MVP++] Alice's party!").type);assertEquals(PartyMessages.Type.NO_PARTY,PartyMessages.parse("You have been removed from the party.").type);}
    @Test public void permissionsProtectLeaderAndPeers(){PartyState s=new PartyState();s.role("Host",Member.Role.LEADER,1);s.role("Mod",Member.Role.MODERATOR,1);Member peer=s.join("Peer",1);assertTrue(s.canRemove("Host",peer));assertTrue(s.canRemove("Mod",peer));assertFalse(s.canRemove("Mod",s.get("Host")));assertFalse(s.canRemove("Mod",s.get("Mod")));assertFalse(s.canRemove("Peer",s.get("Mod")));}
    @Test public void readinessNeedsCurrentRoundAndSender(){PartyState s=new PartyState();Member a=s.join("Alice",1);String old=s.startReadyRound();assertFalse(s.acknowledge("Mallory","ready "+old));assertTrue(s.acknowledge("Alice","ready "+old));s.startReadyRound();assertFalse(a.ready);assertFalse(s.acknowledge("Alice","ready "+old));}
    @Test public void missingDataRemainsUnknown(){PlayerStats s=stats("{}");assertNull(s.networkLevel);assertNull(s.firstLogin);assertNull(s.games());assertNull(s.fkd());assertTrue(ReviewRules.evaluate(s,new ReviewRules.Options(),10000,null).isEmpty());}
    @Test public void malformedFieldsDoNotThrow(){PlayerStats s=stats("{\"firstLogin\":\"bad\",\"networkLevel\":{},\"megaWalls\":{\"wins\":-1,\"losses\":null,\"finalKills\":[],\"finalDeaths\":\"3\"}}");assertNull(s.firstLogin);assertNull(s.networkLevel);assertNull(s.games());assertNull(s.finals);}
    @Test public void documentedFirstLoginIsRetained(){PlayerStats s=stats("{\"firstLogin\":1700000000000,\"_id\":\"short\"}");assertEquals(Long.valueOf(1700000000000L),s.firstLogin);}
    @Test public void zeroDenominatorsAreExplicitlyUnknown(){PlayerStats s=stats("{\"megaWalls\":{\"wins\":20,\"losses\":0,\"finalKills\":100,\"finalDeaths\":0}}");assertNull(s.wl());assertNull(s.fkd());assertEquals(Integer.valueOf(20),s.games());}
    @Test public void allApplicableReasonsAreReturned(){PlayerStats s=stats("{\"firstLogin\":1000,\"networkLevel\":10,\"megaWalls\":{\"wins\":5,\"losses\":5,\"finalKills\":100,\"finalDeaths\":5,\"legendarySkins\":1}}");assertTrue(ReviewRules.evaluate(s,new ReviewRules.Options(),2000,null).size()>=6);}
    @Test public void all27ClassesAreSupported(){assertEquals(27,PlayerStats.CLASSES.length);PlayerStats s=stats("{\"megaWalls\":{\"classes\":{\"dragon\":{\"unlocked\":true,\"kit\":5,\"ability\":5,\"passive1\":3,\"passive2\":3,\"gathering\":3}}}}");assertTrue(s.kits.get("Dragon").maxed());}
    @Test public void lockedAndPartialKitsAreNotMaxed(){PlayerStats.Kit k=new PlayerStats.Kit();k.unlocked=true;k.kit=5;k.ability=5;k.passive1=3;k.passive2=3;k.gathering=1;assertFalse(k.maxed());k.gathering=3;k.unlocked=false;assertFalse(k.maxed());k.unlocked=true;assertTrue(k.maxed());}
    @Test public void freeStarterDoesNotTriggerKitRule(){PlayerStats s=stats("{\"megaWalls\":{\"wins\":0,\"losses\":0,\"classes\":{\"cow\":{\"unlocked\":true,\"kit\":5,\"ability\":5,\"passive1\":3,\"passive2\":3,\"gathering\":3}}}}");ReviewRules.Options o=new ReviewRules.Options();o.lowExperience=false;assertTrue(ReviewRules.evaluate(s,o,1000,null).isEmpty());}
    @Test public void unknownActivityDoesNotFlag(){assertTrue(ReviewRules.evaluate(null,new ReviewRules.Options(),System.currentTimeMillis(),null).isEmpty());}
    @Test public void activityGapHasHonestEvidenceLabel(){long now=System.currentTimeMillis();List<String> r=ReviewRules.evaluate(null,new ReviewRules.Options(),now,now-200*86400000L);assertEquals(1,r.size());assertTrue(r.get(0).contains("outside your events unknown"));}
    @Test public void approvalsInvalidateThroughMaterialReasons(){Member m=new Member("Alice",1,1);m.reasons.add("A");assertTrue(m.needsReview());m.dismissedFingerprint=m.fingerprint();assertFalse(m.needsReview());m.reasons.add("B");assertTrue(m.needsReview());}
    private static class Transport implements ActionQueue.Transport {List<String> sent=new ArrayList<>(),results=new ArrayList<>();boolean valid=true;public boolean valid(ActionQueue.Action a){return valid;}public void send(String command){sent.add(command);}public void result(ActionQueue.Action a,String result){results.add(result);}}
    private ActionQueue.Action action(ActionQueue.Kind kind,String name,long generation,long time){return new ActionQueue.Action(kind,name,"/"+kind.name()+" "+name,generation,1,time);}
    @Test public void commandsWaitForAcknowledgement(){ActionQueue q=new ActionQueue();Transport t=new Transport();q.enqueue(action(ActionQueue.Kind.REMOVE,"A",1,0));q.enqueue(action(ActionQueue.Kind.REMOVE,"B",1,0));q.tick(0,1000,t);q.tick(5000,1000,t);assertEquals(1,t.sent.size());assertTrue(q.acknowledge(ActionQueue.Kind.REMOVE,"A","Confirmed",t));q.tick(5001,1000,t);assertEquals(2,t.sent.size());}
    @Test public void mismatchedAcknowledgementCannotCompleteAction(){ActionQueue q=new ActionQueue();Transport t=new Transport();q.enqueue(action(ActionQueue.Kind.REMOVE,"A",1,0));q.tick(0,1000,t);assertFalse(q.acknowledge(ActionQueue.Kind.REMOVE,"B","Confirmed",t));assertNotNull(q.pending());}
    @Test public void duplicateKicksCannotDuplicateBlock(){ActionQueue q=new ActionQueue();assertTrue(q.enqueue(action(ActionQueue.Kind.BLOCK,"A",1,0)));assertFalse(q.enqueue(action(ActionQueue.Kind.BLOCK,"a",1,1)));Transport t=new Transport();q.tick(2,1000,t);q.acknowledge(ActionQueue.Kind.BLOCK,"A","Confirmed",t);assertFalse(q.enqueue(action(ActionQueue.Kind.BLOCK,"A",1,5000)));assertTrue(q.enqueue(action(ActionQueue.Kind.BLOCK,"A",2,5001)));}
    @Test public void hundredBlocksSurviveSerializedAcknowledgementTimeouts(){ActionQueue q=new ActionQueue();Transport t=new Transport();for(int i=0;i<100;i++)assertTrue(q.enqueue(action(ActionQueue.Kind.BLOCK,"P"+i,1,0)));for(int i=0;i<100;i++){long now=i*13000L;q.tick(now,3000,t);q.tick(now+10000,3000,t);}assertEquals(100,t.sent.size());assertTrue(t.results.stream().allMatch(r->r.startsWith("Unconfirmed")));}
    @Test public void cancelledCommandsAreNeverSent(){ActionQueue q=new ActionQueue();Transport t=new Transport();q.enqueue(action(ActionQueue.Kind.REMOVE,"A",1,0));q.cancel(t);q.tick(1,1000,t);assertTrue(t.sent.isEmpty());assertEquals(0,q.size());}
    @Test public void contextChangedCommandsAreDropped(){ActionQueue q=new ActionQueue();Transport t=new Transport();t.valid=false;q.enqueue(action(ActionQueue.Kind.REMOVE,"A",1,0));q.tick(1,1000,t);assertTrue(t.sent.isEmpty());assertTrue(t.results.get(0).startsWith("Cancelled"));}
    @Test public void actionsHaveBoundedQueue(){ActionQueue q=new ActionQueue();for(int i=0;i<128;i++)assertTrue(q.enqueue(action(ActionQueue.Kind.REMOVE,"P"+i,1,0)));assertFalse(q.enqueue(action(ActionQueue.Kind.REMOVE,"Overflow",1,0)));}
    @Test public void unconfirmedActionsDoNotRetryBlindly(){ActionQueue q=new ActionQueue();Transport t=new Transport();q.enqueue(action(ActionQueue.Kind.REMOVE,"A",1,0));q.tick(0,1000,t);q.tick(10001,1000,t);q.tick(30000,1000,t);assertEquals(1,t.sent.size());assertNull(q.pending());assertTrue(t.results.get(0).startsWith("Unconfirmed"));}
    @Test public void serviceUrlDoesNotLeakTokensThroughRedirectsOrUserinfo(){DataClient.validateEndpoint("https://service.example");DataClient.validateEndpoint("http://127.0.0.1:8080");for(String bad:new String[]{"http://service.example","https://user:secret@service.example","https://service.example?key=secret","file:///tmp/data"})try{DataClient.validateEndpoint(bad);fail(bad);}catch(IllegalArgumentException expected){}}
}
