package fr.alexdoru.partymod;

import fr.alexdoru.partymod.core.*;
import fr.alexdoru.partymod.data.LocalStore;
import org.junit.*;
import org.junit.rules.TemporaryFolder;
import static org.junit.Assert.*;
import java.io.File;
import java.util.Collections;

public class SecondInteractionTest {
    @Rule public TemporaryFolder temp=new TemporaryFolder();
    private String uuid="00000000000000000000000000000001";
    private File file(){return new File(temp.getRoot(),"records.json");}
    private PartyState party(){PartyState s=new PartyState();s.role("Host",Member.Role.LEADER,1);s.join("Alice",1);return s;}
    @Test public void joinsBeforeUuidResolutionAddOnceToExistingHistory(){LocalStore store=new LocalStore(file());Member m=new Member("Alice",1,1);LocalStore.Record old=new LocalStore.Record();old.uuid=uuid;old.joins=100;store.records.put("uuid:"+uuid,old);store.observePartyJoin(m,2);m.uuid=uuid;assertEquals(101,store.record(m).joins);assertEquals(101,store.record(m).joins);store.flush(true);assertEquals(101,new LocalStore(file()).record(m).joins);}
    @Test public void sightingsBeforeResolutionAddOnceToExistingHistory(){LocalStore store=new LocalStore(file());Member m=new Member("Alice",1,1);LocalStore.Record old=new LocalStore.Record();old.uuid=uuid;old.mwSightings=100;store.records.put("uuid:"+uuid,old);store.observeMwSighting(m,2);store.observeMwSighting(m,3);m.uuid=uuid;assertEquals(102,store.record(m).mwSightings);assertEquals(102,store.record(m).mwSightings);}
    @Test public void retainedLongNotesDoNotReplayPendingCounts(){LocalStore store=new LocalStore(file());Member m=new Member("Alice",1,1);LocalStore.Record old=new LocalStore.Record();old.uuid=uuid;old.joins=100;old.note=String.join("",Collections.nCopies(1000,"a"));store.records.put("uuid:"+uuid,old);store.observePartyJoin(m,2);store.record(m).note=String.join("",Collections.nCopies(1000,"b"));m.uuid=uuid;assertEquals(101,store.record(m).joins);for(int i=0;i<10;i++)assertEquals(101,store.record(m).joins);store.flush(true);assertEquals(101,new LocalStore(file()).record(m).joins);}
    @Test public void unresolvedNoteSurvivesRestartWithoutInheritingOldOwner(){LocalStore store=new LocalStore(file());LocalStore.Record old=new LocalStore.Record();old.uuid=uuid;old.note="Old owner";store.records.put("name:alice",old);Member m=new Member("Alice",1,1);store.record(m).note="Current unknown member";store.touch();store.flush(true);LocalStore loaded=new LocalStore(file());assertEquals("Current unknown member",loaded.record(m).note);assertEquals("Old owner",loaded.records.get("name:alice").note);}
    @Test public void migrationRetainsSecondaryNotesOnTheFallbackRecord(){LocalStore store=new LocalStore(file());Member m=new Member("Alice",1,1);LocalStore.Record fallback=store.record(m);fallback.note="Primary";fallback.migratedNote="Earlier retained note";m.uuid=uuid;assertEquals("Earlier retained note",store.record(m).migratedNote);store.flush(true);LocalStore loaded=new LocalStore(file());assertEquals("Earlier retained note",loaded.record(m).migratedNote);assertEquals("Earlier retained note",loaded.records.get("name:alice").migratedNote);}
    @Test public void retainedSecondaryNotesDoNotRepeatAMergedPrimary(){LocalStore store=new LocalStore(file());Member m=new Member("Alice",1,1);LocalStore.Record fallback=store.record(m);fallback.note="Primary";fallback.migratedNote="Earlier retained note";LocalStore.Record current=new LocalStore.Record();current.note="Canonical";current.uuid=uuid;store.records.put("uuid:"+uuid,current);m.uuid=uuid;for(int i=0;i<10;i++)assertEquals("Canonical | Primary",store.record(m).note);store.flush(true);assertEquals("Canonical | Primary",new LocalStore(file()).record(m).note);}
    @Test public void retainedPendingNotesCannotBecomeANewUnknownMembersHistory(){LocalStore store=new LocalStore(file());LocalStore.Record former=new LocalStore.Record();former.uuid=uuid;former.note="Former owner";store.records.put("name:alice",former);String currentUuid="00000000000000000000000000000002";LocalStore.Record canonical=new LocalStore.Record();canonical.uuid=currentUuid;canonical.note=String.join("",Collections.nCopies(1000,"a"));store.records.put("uuid:"+currentUuid,canonical);Member m=new Member("Alice",1,1);String pendingNote=String.join("",Collections.nCopies(1000,"b"));store.record(m).note=pendingNote;m.uuid=currentUuid;assertEquals(pendingNote,store.record(m).migratedNote);assertFalse(store.records.containsKey("pending:alice"));store.flush(true);LocalStore loaded=new LocalStore(file());assertEquals("",loaded.record(new Member("Alice",2,2)).note);assertTrue(loaded.records.values().stream().anyMatch(r->currentUuid.equals(r.uuid)&&pendingNote.equals(r.note)));loaded.delete(m);assertFalse(loaded.records.values().stream().anyMatch(r->currentUuid.equals(r.uuid)));assertEquals("Former owner",loaded.records.get("name:alice").note);}
    @Test public void deletingUnresolvedHistoryCannotDeleteAnOwnedAlias(){LocalStore store=new LocalStore(file());LocalStore.Record old=new LocalStore.Record();old.uuid=uuid;store.records.put("name:alice",old);Member m=new Member("Alice",1,1);store.record(m).note="Pending";store.delete(m);assertEquals(1,store.records.size());assertSame(old,store.records.get("name:alice"));}
    @Test public void failedReadySendClearsOnlyItsOwnRound(){PartyState s=party();String old=s.startReadyRound();s.get("Host").ready=true;s.readyResult(old,false);assertEquals("",s.round);assertFalse(s.get("Host").ready);String newer=s.startReadyRound();s.readyResult(old,false);assertEquals(newer,s.round);s.readyResult(newer,true);assertEquals(newer,s.round);}
    @Test public void visibleActionRejectsChangedUuid(){PartyState s=party();Member m=s.get("Alice");MemberTicket t=new MemberTicket(s,m);assertTrue(t.valid(s));m.uuid=uuid;assertFalse(t.valid(s));}
    @Test public void visibleActionRejectsChangedEvidence(){PartyState s=party();Member m=s.get("Alice");MemberTicket t=new MemberTicket(s,m);m.reasons.add("New reason");assertFalse(t.valid(s));}
    @Test public void visibleActionRejectsRejoinAndCancelledSession(){PartyState s=party();MemberTicket t=new MemberTicket(s,s.get("Alice"));s.leave("Alice");s.join("Alice",2);assertFalse(t.valid(s));t=new MemberTicket(s,s.get("Alice"));s.invalidateWork();assertFalse(t.valid(s));}
}
